[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
s3-bucket = { workspace = true }
aws-config = "1.8.12"
aws-sdk-s3 = "1.119.0"
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
tokio = { version = "1.49.0", features = ["full"] }
